/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.sweeper.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */
#include "sweeperadaptor.h"
#include "sweeperadaptor.moc"

KsweeperAdaptor::KsweeperAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KsweeperAdaptor::~KsweeperAdaptor()
{
    // destructor
}

void KsweeperAdaptor::cleanup()
{
    // handle method call org.kde.ksweeper.cleanup
    QMetaObject::invokeMethod(parent(), "cleanup");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->cleanup();
}

