/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.sweeper.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef SWEEPERADAPTOR_H_315251149513045
#define SWEEPERADAPTOR_H_315251149513045

#include <QtCore/QObject>
#include <QtCore/QMetaObject>
#include <QtCore/QVariant>
#include <dbus/qdbus.h>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Adaptor class for interface org.kde.ksweeper
 */
class KsweeperAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.ksweeper")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.ksweeper\" >\n"
"    <method name=\"cleanup\" />\n"
"  </interface>\n"
        "")
public:
    KsweeperAdaptor(QObject *parent);
    virtual ~KsweeperAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void cleanup();
Q_SIGNALS: // SIGNALS
};

#endif
